[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    mikalhart/TinyGPSPlus@^1.0.3
    h2zero/NimBLE-Arduino@^1.4.3

[env:demo_usb]
extends = env:esp32dev
build_flags =
    -DDEMO_NO_BROWNOUT
